<!-- <div class="container"> -->
	<div class="row">
		<div class="col s12 ">
			<div id="index-banner" class="parallax-container">
        <div class="section no-pad-bot">
          <div class="container">
            <br><br>
            <h1 class="header center blue-grey-text text-darken-3">Contabilidad Manual</h1>
            <div class="row center">
              <h5 class="header col s12 light blue-grey-text text-darken-3">¿Deseas ingresar movimientos de forma manual?</h5>
            </div>
            <div class="row center">
              <a href="<?php echo BASE_URL; ?>manual" id="download-button" class="btn-large waves-effect waves-light  lime blue-grey-text">Iniciar</a>
            </div>
            <br><br>

          </div>
        </div>
        <div class="parallax"><img src="http://wallpapercave.com/wp/stMi7Lu.jpg" alt="Unsplashed background img 1"></div>
      </div>
		</div>
	</div>
  <div class="row">
    <div class="col s12 l6">
      <div id="index-banner" class="parallax-container">
        <div class="section no-pad-bot">
          <div class="container">
            <br><br>
            <h1 class="header center blue-grey-text text-darken-3">Cuentas PUC</h1>
            <div class="row center">
              <h5 class="header col s12 light blue-grey-text text-darken-3">Plan único de cuentas</h5>
            </div>
            <div class="row center">
              <a href="<?php echo BASE_URL; ?>puc/consultar" id="download-button" class="btn btn-large btn-flat lime-text">Consultar</a>
              <a href="<?php echo BASE_URL; ?>puc" id="download-button" class="btn btn-large btn-flat lime-text">Regristrar</a>
            </div>
            <br><br>

          </div>
        </div>
        <div class="parallax"><img src="https://wallpaperscraft.com/image/sports_car_race_speed_81253_1280x800.jpg" alt="Unsplashed background img 1"></div>
      </div>
    </div><div class="col s12 l6">
      <div id="index-banner" class="parallax-container">
        <div class="section no-pad-bot">
          <div class="container">
            <br><br>
            <h1 class="header center blue-grey-text text-darken-3">Registro de nuevo usuario</h1>
            <div class="row center">
              <a href="<?php echo BASE_URL; ?>registro" id="download-button" class="btn btn-large  lime blue-grey-text">Agregar</a>
            </div>
            <br><br>

          </div>
        </div>
        <div class="parallax"><img src="https://static.pexels.com/photos/25231/pexels-photo-25231.jpg" height="768" alt="Unsplashed background img 1"></div>
      </div>
    </div>
  </div>
<!-- </div> -->