<section>
		<div class="container">
			<div class="row">

				<div class="col s12 l6 hide-on-med-and-down">
                	<img src="http://i.imgur.com/JR3DJho.jpg" alt="" class="imagen">
                </div>

				<div class="col s12 l6">
                    <h1 class="nombre blue-grey-text center-align">Drink and Fair Play</h1>
                    <h4 class="loginTexto center-align lime-text">Iniciar sesión</h4>
                    		
                    <form action="" method="post" id="form-login" class="form-horizontal">
                        <input type="hidden" value="1" name="enviar" />
                        <input type="text" id="login-email" name="login-email" class="form-control input-lg" placeholder="Email" value="<?php if(isset($this->datos)) echo $this->datos['login-email']; ?>">
                        <input type="password" id="password" name="login-password" class="form-control input-lg" placeholder="Password">                   
                            
                        <label class="switch switch-primary" data-toggle="tooltip" title="Recordarme?">
                        	<input type="checkbox" id="login-remember-me" name="login-remember-me" checked>
                        </label>
						
                        <div class="row center">
                            <button type="submit" class="btn btn-sm btn-primary lime-text blue-grey"></i> Ingresar</button>
                        </div>
						

						<p class="flow-text center-align">Lleva tu contabilidad a donde desees, recuerda que esta aplicación es 100% adaptable a tu dispositivo</p>
                    </form>
                </div>

                
			</div>
		</div>
</section>