<div class="container">
    <div class="row">
        <div class="col s12">
            <h3>Contabilidad Manual</h3>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            <form name="form1" method="post" action="">
            <input type="hidden" value="1" name="guardar" />
            <input type="text" value="<?php if(isset($this->datos)) {echo $this->datos['i'];}else{echo 0;} ?>" id="i" name="i" />
            <input type="text" value="0" id="debito" name="debito"/>
            <input type="text" value="0" id="credito" name="credito"/>

            
            <div class="row">
                <div class="col s12 l4">
                    <label>Fecha: &nbsp; </label>
                    <input type="date" name="fecha" value="<?php if(isset($this->datos)) echo $this->datos['fecha']; ?>" required>
                </div>
                <div class="col s12 l4">
                    <label>No. Documento: &nbsp; </label>
                    <input type="text" class="form-control" name="documento" value="<?php if(isset($this->datos)) echo $this->datos['documento']; ?>" placeholder="No. documento" required>
                </div>
                <!-- <div class="col s12 l4">
                    <label>&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;Consecutivo:  </label>
                    <font color="red">001 </font>
                </div> -->
            </div>
            <div class="row">
                <div class="col s12">
                    <label>Descripción:  &nbsp; </label>
                    <input type="text" class="form-control" name="descripcion" value="<?php if(isset($this->datos)) echo $this->datos['descripcion']; ?>" placeholder="Descripción" required>
                </div>
            </div>

            <div class="row">
                <div class="col s12">
                    <table id="cuentas" class="table table-bordered center">
                        <thead>
                            <th>Cuenta</th>
                            <th>Nombre</th>
                            <th>Valor</th>
                            <th>Naturaleza</th>

                        </thead>

        
                        <tr>
                            <td>
                                <select id="cuenta0"  class="form-control" name="cuenta0">
                                    <option value="0" disabled selected>Seleccione...</option>
                                    <?php for($i = 0; $i < count($this->puc); $i++): ?>
                                    <option value="<?php echo $this->puc[$i]['id']; ?>"><?php echo $this->puc[$i]['codigo']." ".$this->puc[$i]['nombre']; ?></option>          
                                    <?php endfor;?>
                                </select>
                            </td>
                            <td>
                                <input id="nombre0" type="text" class="form-control" name="nombre0" value="<?php if(isset($this->datos)) echo $this->datos['nombre0']; ?>" placeholder="Cuenta..." required>
                            </td>
                            <td>
                                <input id="valor0" type="text" class="form-control" name="valor0" value="<?php if(isset($this->datos)) echo $this->datos['valor0']; ?>" placeholder="1000" required>
                            </td>
                            <td>
                                <select id="naturaleza0" class="form-control" name="naturaleza0">
                                    <option value="0" disabled selected>Seleccione...</option>
                                    <option value="1"> Debito </option>          
                                    <option value="2"> Credito </option>          
                  
                                </select>
                            </td>
                        </tr>

                    </table>
                </div>
            </div>

            <div class="row">
                <div class="col s12 l6">
                    <label for=""><a href="#" class="teal-text" id="AgregarCampos">Agregar Campos</a></label>
                    &nbsp;&nbsp;&nbsp;
                    <label for=""><a href="#" class="teal-text" id="QuitarCampos">Quitar Campos</a></label>
                </div>
                <div class="col s12 l6">
                    <button type="submit" onclick="ValidarCuentas();" class="btn btn-default">Guardar</button>
                </div>
            </div>
            </form>

            <script >
                var nextinput = 0;

                function AgregarCampos(){
                    nextinput++;
                    //campos = '<input type="text" size="20" id="campo' + nextinput + '"&nbsp; name="campo' + nextinput + '"&nbsp; />';
            //$('#tablaSocioeconomica tr:last').after();
                    campos = '<tr id="campo' + nextinput + '">'+
                                '<td> '+
                                '    <select id="cuenta' + nextinput + '" class="form-control" name="cuenta' + nextinput + '">'+
                                '      <option value="0" disabled selected>Seleccione...</option>'+
                                '      <?php for($i = 0; $i < count($this->puc); $i++): ?>'+
                                '        <option value="<?php echo $this->puc[$i]['id']; ?>"><?php echo $this->puc[$i]['codigo']." ".$this->puc[$i]['nombre']; ?></option>  '+        
                                '      <?php endfor;?>'+
                                '    </select> '+
                                '</td> '+
                                '<td> '+
                                '    <input id="nombre' + nextinput + '" type="text" class="form-control" name="nombre' + nextinput + '"  placeholder="Cuenta..." required /> '+
                                '</td> '+
                                '<td> '+
                                '    <input id="valor' + nextinput + '" type="text" class="form-control" name="valor' + nextinput + '"  placeholder="1000" required /> '+
                                '</td> '+
                                '<td> '+
                                '    <select id="naturaleza' + nextinput + '" class="form-control" name="naturaleza' + nextinput + '"> '+
                                '      <option value="0" disabled selected>Seleccione...</option> '+
                                '      <option value="1"> Debito </option>  '+
                                '      <option value="2"> Credito </option>  '+       
                                      
                                '   </select> '+
                                '</td> '+
                            '</tr>';
                    $("#cuentas").append(campos);
                    $("#i").val(nextinput);
                }

                $("#AgregarCampos").click(AgregarCampos);

                function QuitarCampos(){
                    if (nextinput > 0){

                        $("#campo"+nextinput).remove(); 
                        nextinput--;
                        $("#i").val(nextinput);
                    }
                }

                $("#AgregarCampos").click(AgregarCampos);

                var debito=0;
                var credito=0;

                function ValidarCuentas(){

                    for (var i = 0; i <= $("#i").val(); i++) {
                        if ($("#naturaleza"+i).val() == '1') {
                            debito = debito + parseInt($("#valor"+i).val(),10);
                        }else{
                            credito = credito + parseInt($("#valor"+i).val(),10);
                        }
                    }

                    if (credito != debito) {
                        alert("Estan desbalanceadas!!  Debito: "+debito+ " Credito: "+credito);
                    }

                    $("#debito").val(debito);
                    $("#credito").val(credito);

                    
                }



            </script>
            <div class="row">
                <div class="col s12">
                    <table class="table table-bordered center">
                        <thead>
                            <th>Cuenta</th>
                            <th>Nombre</th>
                            <th>Valor</th>
                            <th>Naturaleza</th>

                        </thead>
        
                        <?php if (isset(($this->consultar))): ?>
                            
                        
                        <?php for($i = 0; $i < count($this->consultar); $i++): ?>
        
                        <tr>
                            <td><?php echo $this->consultar[$i]['cuenta']; ?></td>
                            <td><?php echo $this->consultar[$i]['nombre']; ?></td>
                            <td><?php echo $this->consultar[$i]['Valor']; ?></td>
                            <td><?php echo $this->consultar[$i]['Naturaleza']; ?></td>
                        </tr>
        
                        <?php endfor;?>
                        <?php endif ?>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>



    
