<nav>
    <div class="nav-wrapper grey lighten-1">
        <div class="col s12">
            <a href="<?php echo BASE_URL; ?>puc" class="breadcrumb"><i class="material-icons">mode_edit</i>Registrar</a>
            
        </div>
    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col s12">
            <h4>Consultar: </h4>

            <form name="form1" method="post" action="">
                <input type="hidden" value="1" name="consultar" />
    
                <p>
                    <input type="text" name="valor" placeholder="Buscar Cuenta..." />
                    <input type="submit" value="Consultar" class="btn lime darken-1" />
                </p>

            </form>
            <?php if (count($this->consultar)!=0): ?>
    
            <h4>Cuentas: </h4>

            <table class="striped">
                <thead>
                    <th>C&Oacute;DIGO</th>
                    <th>NOMBRE</th>
                    
                </thead>

                <?php for($i = 0; $i < count($this->consultar); $i++): ?>
            
                <tr>
                    <td><?php echo $this->consultar[$i]['codigo']; ?></td>
                    <td><?php echo $this->consultar[$i]['nombre']; ?></td>
                    
                </tr>
            
                <?php endfor;?>
            </table>

            <?php endif ?>
        </div>
    </div>
</div>


